In [1]:
import numpy
import time
from datetime import datetime, timedelta
import scipy.io
import csv

from nsopy.methods.subgradient import SubgradientMethod
from nsopy.loggers import GenericMethodLogger

# Author: Renzo Caballero
# KAUST: King Abdullah University of Science and Technology
# email 1: renzo.caballerorosas@kaust.edu.sa
# email 2: CaballeroRenzo@hotmail.com
# email 3: CaballeroRen@gmail.com
# Website: None
# November 2019; Last revision: 05/12/2019

In [2]:
def oracle(x):
    
    # We load data from the previous optimization:
    path = ['Simulations/table_',actualDate,'.mat']
    path = "".join(path)
    mat = scipy.io.loadmat(path)
    array = mat.get('saveTable')
    lastRow = array[-1]
    auxSft = lastRow[0:4]
    sft = numpy.array([val for val in auxSft for _ in (0, 1)])
      
    if len(x) == 1:
        x = x[0]
    
    comm = numpy.asarray([x[0]+sft[0],x[1]+sft[1],x[2]+sft[2],x[3]+sft[3], # 4
                          x[4]+sft[4],x[5]+sft[5],x[6]+sft[6],x[7]+sft[7], # 4
                          0,0,0,0,0,0,0,0,0,0]);
    numpy.savetxt("loopForOpt_2.csv", comm, delimiter=",");
    done = 0;

    while done == 0:

        time.sleep(20);
        comm = numpy.loadtxt("loopForOpt_2.csv", delimiter =', ');

        if float(comm[-1]) == 1:
            print(comm[0:8]);
            print(comm[9:17]);
            print(comm[8]);
            done = 1;
        else:
            print('Waiting for MATLAB...');
            
    f_x_k = comm[8];
    diff_f_xk = [comm[9:17]];
    
    return 0, f_x_k, numpy.array(diff_f_xk)

def projection_function(x_k):
    if x_k is 0:
        return numpy.array([0,])
    else:
        return numpy.maximum(x_k, 0)

In [3]:
initialDate = "20180308"
#initialDate = "20180405"
finalDate = "20180505"
#finalDate = "20191130"
dateStringFormat = '%Y%m%d'

actualDate = initialDate

while actualDate != finalDate:
    
    # Create .csv file with the date that we will compute:
    myFile = open('date_2.csv', 'w')
    with myFile:
        writer = csv.writer(myFile)
        writer.writerows([[actualDate]])
    
    # Create path and load .mat file:
    path = ['Historical/dailyData/Day_',actualDate,'.mat']
    path = "".join(path)
    mat = scipy.io.loadmat(path)
    # We use only the dams costs and create the step:
    array = mat.get("Matrix")
    array = array[0]
    array = array[2]
    div = 0.0025
    step = numpy.mean(array) / div
    # If all dams have value zero, we set the steo to 1:
    if step == 0:
        step = 1

    method = SubgradientMethod(oracle, projection_function, dimension=8, stepsize_0=step, stepsize_rule="1/k", sense='min')
    logger = GenericMethodLogger(method)

    for iteration in range(5):
        method.step()
        
    # We increment the actualDate in one day:
    actualDate = datetime.strptime(actualDate, dateStringFormat)
    actualDate = actualDate + timedelta(days=1)
    actualDate = actualDate.strftime(dateStringFormat)


Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[  0.     0.     0.     0.   284.29 284.29 357.22 357.22]
[ 0.82115   0.55693   1.1046    1.0812   -0.       -0.       -0.
 -0.036605]
-55.894
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...

Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[   0.      0.      0.      0.    281.57  281.57  316.92 1789.4 ]
[ 1.5374e-17  1.5763e-17  8.8351e-01  1.0833e+00 -0.0000e+00 -1.1642e-17
 -2.3283e-17 -3.6637e-02]
-98.705
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[   0.      0.      0.      0.    281.57  281.57  316.92 

Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[   0.      0.      0.      0.    280.8   280.8   407.18 3158.5 ]
[ 1.2859e-02  5.1100e-01  1.1057e+00  1.0824e+00 -1.0477e-16 -2.3283e-17
 -0.0000e+00 -3.6541e-02]
-168.27
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for M

Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[   0.      0.      0.      0.    280.28  280.28  406.47 3528.  ]
[ 1.4076e-01  1.1760e-01  1.1007e+00  1.0312e+00 -4.6566e-17 -8.1491e-17
 -8.1491e-17 -3.6262e-02]
474.95
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[  0.      0.     19.218  19.218 281.6   281.6   322.8   322.8  ]
[ 2.9844e-03  

Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[   0.      0.      0.      0.    299.7   299.7   431.76 3147.1 ]
[ 1.1587e-02  7.1005e-01  1.1017e+00  1.0783e+00 -1.0477e-16 -9.3132e-17
 -0.0000e+00 -3.5620e-02]
125.04
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MA

Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[  0.     0.     0.     0.   247.42 247.42 265.66 265.66]
[ 2.4473e-19  1.5087e-01  6.6372e-01  9.8642e-01 -3.4925e-17 -0.0000e+00
 -0.0000e+00 -3.8615e-02]
730.87
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[   0.      0.      0.      0.    247.42  247.42  265.66 1608.7 ]
[ 4.3717e-18  1.5087e-01  6.6372e-01  9.8642e-01 -2.3283e-17 -0.00

Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[  0.        0.        0.91267   0.91267 312.94    312.94    335.68
 335.68   ]
[ 3.7226e-29  9.2640e-18  1.6056e-17  1.1629e-01 -0.0000e+00 -0.0000e+00
 -8.1491e-17 -3.8663e-02]
945.45
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[0.0000e+00 0.0000e+00 9.1267e-01 9.1267e-01 3.1294e+02 3.1294e+02

Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[   0.      0.      0.      0.    319.28  319.28  337.2  2893.8 ]
[ 3.4365e-18  2.1575e-18  6.6867e-02  4.1898e-01 -1.1642e-17 -1.1642e-17
 -3.4925e-17 -3.8834e-02]
672.66
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MA

Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[   0.        0.        8.4447    8.4447  118.7     118.7     139.81
 1615.3   ]
[ 3.9928e-17  2.1616e-17  2.6470e-17  3.2255e-17 -1.1642e-16 -6.9849e-17
 -1.9791e-16 -3.8829e-02]
600.53
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
Waiting for MATLAB...
[  0.     0.     0.     0.   154.13 154.13 203.54 203.54]
[ 2.2656e-17  1.2152e-01  3.6489e-01  2.8823e-01 -4.6566e-17 -2.3283e-17
 -1.1642e-16 -3.5742e-02]
524.17
Waiting for MATLAB...
Waiting for

KeyboardInterrupt: 